from pydantic import BaseModel, Field


class ScoutResult(BaseModel):
    """
    Structured output generated by the Scout Agent.
    """

    search_queries: list[str] = Field(
        description="A list of focused search queries for researching the user's topic."
    )